# File: .github/workflows/main.yaml
name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        echo "⚠️ No tests yet. Add your unit tests here."
        # pytest or unittest can go here when you're ready!

  deploy:
    name: Deploy to Render
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Render
      uses: render-examples/deploy-to-render-action@v1.3.2
      with:
        service_id: ${{ secrets.RENDER_SERVICE_ID }}
        api_key: ${{ secrets.RENDER_API_KEY }} 
